CANONICAL_ALIASES = {
    "lens_type": {
        "single vision": "Single Vision Lenses",
        "single vision lens": "Single Vision Lenses",
        "single vision lenses": "Single Vision Lenses",
        "progressive": "Progressive Lenses",
        "progressive lens": "Progressive Lenses",
        "progressive lenses": "Progressive Lenses",
        "blue light": "Blue Light Protection",
        "blue light lens": "Blue Light Protection",
        "blue light lenses": "Blue Light Protection",
        "blue light protection": "Blue Light Protection",
        "photochromic": "Photochromic Lenses",
        "photochromic lens": "Photochromic Lenses",
        "photochromic lenses": "Photochromic Lenses",
    },
    "product_type": {
        "designer frame": "Frames",
        "designer frames": "Frames",
        "frames": "Frames",
        "frame": "Frames",
        "glasses": "Frames",
        "spectacles": "Frames",
        "eyeglasses": "Frames",
        "blue light glasses": "Frames",
        "office glasses": "Frames",
        "office wear glasses": "Frames",
        "work glasses": "Frames",
        "computer glasses": "Frames",
        "gaming glasses": "Frames",
        "luxury sunglasses": "Sunglasses",
        "sunglasses": "Sunglasses",
        "sunglass": "Sunglasses",
        "shades": "Sunglasses",
        "sun glasses": "Sunglasses",
        "cermin mata hitam": "Sunglasses",
        "太阳镜": "Sunglasses",
        "contact lenses": "Contact Lenses",
        "contact lens": "Contact Lenses",
        "contacts": "Contact Lenses",
        "kanta sentuh": "Contact Lenses",
        "隐形眼镜": "Contact Lenses",
    },
    "preferred_service": {
        "designer frame": "Designer Frames",
        "designer frames": "Designer Frames",
        "luxury sunglasses": "Luxury Sunglasses",
        "sunglasses": "Luxury Sunglasses",
        "lens": "Lens Consultation",
        "lens consultation": "Lens Consultation",
        "eyewear recommendation": "Eyewear Recommendation",
        "store visit": "Store Visit",
        "after sales support": "After-sales Support",
        "after sales": "After-sales Support",
        "appointment booking": "Appointment Booking",
        "appointment reschedule": "Appointment Reschedule",
        "consultant support": "Consultant Support",
        "order tracking": "Order Tracking",
    },
}

NORMALIZATION_MAP = {
    "guci": "gucci",
    "rayban": "ray-ban",
    "sunglass": "sunglasses",
    "sun glass": "sunglasses",
    "contacts": "contact lenses",
    "contact lens": "contact lenses",
    "contct lens": "contact lenses",
    "kontak lens": "contact lenses",
    "bluelight": "blue light",
    "blue-light": "blue light",
    "cermin mata hitam": "sunglasses",
    "bingkai": "frames",
    "kanta sentuh": "contact lenses",
    "太阳镜": "sunglasses",
    "镜框": "frames",
}

PRODUCT_FIELD_ALIASES = {
    "productId": "product_id",
    "productName": "product_name",
    "productType": "product_type",
    "priceMyr": "price_myr",
    "frameMaterial": "frame_material",
    "frameShape": "frame_shape",
    "frameColor": "frame_color",
    "uvProtection": "uv_protection",
    "lensColor": "lens_color",
    "frameStyle": "frame_style",
    "lensType": "lens_type",
    "lensFeature": "lens_feature",
    "lensDuration": "lens_duration",
    "storeLocation": "store_location",
    "stockStatus": "stock_status",
    "newArrival": "new_arrival",
    "fallbackImageUrl": "fallback_image_url",
}

SUPPORT_KEYWORDS = {
    "return", "refund", "exchange", "repair", "warranty", "broken", 
    "damaged", "support", "scratched", "cracked", "cancel order", 
    "defective", "after sales", "after-sales", "order tracking", 
    "track order", "tracking", "complaint", "cancel", "wrong size", "different frame"
}

SUPPORT_INTENT_MAP = {
    "return_request": ["return", "send back"],
    "refund_request": ["refund", "reimbursement", "money back"],
    "exchange_request": ["exchange", "swap", "replace", "wrong size", "different frame"],
    "warranty_support": ["warranty", "claim warranty"],
    "repair_support": ["repair", "broken", "damaged", "scratched", "cracked", "defective", "fix", "loose frame", "bent"],
    "order_support": ["cancel order", "order tracking", "track order", "tracking", "delivery", "shipment", "order problem"],
    "after_sales_support": ["after sales", "after-sales", "support", "complaint", "help with my order"],
}

SUPPORT_INTENTS = set(SUPPORT_INTENT_MAP.keys()) | {
    "after_sales_support",
    "warranty_support",
    "order_tracking",
}
